# Errorboundary

# 결론

React Hooks가 대세이긴 하나, Class 컴포넌트 형식 개발이 필요하다는 걸 느낌

# Class 형식이 필요한 이유

Class 형식이 필요한 이유가 무엇인가에 대해 간단히 설명하자면, 한마디로 Hooks에서 지원하는 방식으로는 오류 발생시 제어할 방법이 없다. 

### 아래 3가지 라이프 사이클이 아직은 Hooks에 구현되지 않았음.

- getSnapshotBeforeUpdate: 가장 마지막으로 렌더링 된 결과가 DOM등에 반영 되었을때 호출
- getDerivedStateFromError: 하위의 자손 컴포넌트에서 오류가 발생했을 때 render 단계에서 호출
- componentDidCatch: 하위의 자손 컴포넌트에서 오류가 발생했을 때 commit 단계에서 호출

<aside>
💡 - Render 단계는 React가 DOM갱신이 일어날 때 이전과 이후를 비교하며 변경 사항을 계산하는 단계
- Commit 단계는 React가 비교를 끝내고 DOM에 직접적으로 갱신될 내용을 적용하는 단계

</aside>

# 라이브러활용 - Preact 영감받아 만들었다고 함

react18에서도 여전히 지원 안함

[https://www.npmjs.com/package/react-use-error-boundary?activeTab=readme](https://www.npmjs.com/package/react-use-error-boundary?activeTab=readme)

```tsx
// install 
npm i react-use-error-boundary
```

```tsx
const [error] = useErrorBoundary((error, errorInfo) =>
  logErrorToMyService(error, errorInfo)
);

// =========================================================

import { withErrorBoundary, useErrorBoundary } from "react-use-error-boundary";

const App = withErrorBoundary(({ children }) => {
  const [error, resetError] = useErrorBoundary(
    // You can optionally log the error to an error reporting service
    (error, errorInfo) => logErrorToMyService(error, errorInfo)
  );

  if (error) {
    return (
      <div>
        <p>{error.message}</p>
        <button onClick={resetError}>Try again</button>
      </div>
    );
  }

  return <div>{children}</div>;
});

// =========================================================

import {
  ErrorBoundaryContext,
  useErrorBoundary,
} from "react-use-error-boundary";

const App = ({ children }) => {
  // ... see function body in example above
};

export default (
  <ErrorBoundaryContext>
    <App />
  </ErrorBoundaryContext>
);
```

# 배경

과거에는 컴포넌트 내부의 자바스크립트 에러가 react의 내부 상태를 훼손하고 다음 렌더링에서 암호화 에러 방출을 유발 했다. 이러한 에러는 항상 애플리케이션 코드의 이전 단계의 에러로 인해 발생했지만, react는 컴포넌트 내에서 에러를 정상적으로 처리할 수 있는 방법을 제공하지 않아 이를 복구할 수가 없었다.

# 에러 경계의 소개

UI의 일부분에 존재하는 자바스크립트 에러가 전체 애플리케이션을 중단 시켜서는 안된다고 판단.

React16에서는 에러 경계라는 새로운 개념을 도입함.

## 에러경계 케이스

- 하위 컴포넌트 트리의 어디에서든 자바스크립트 에러를 기록하며 깨진 컴포넌트 트리 대신 폴백 UI를 보여주는 React 컴포넌트 이다.
- 에러 경계는 렌더링 도중 생명주기 메서드 및 그 아래에 있는 전체 트리에서 에러를 잡아 냄

## 에러경계 아닌 경우

- 이벤트 핸들러
- 비동기적 코*드(setTimeout, setInterval… )*
- *서버사이트 랜더링*
- *자식에서가 아닌 에러 경계 자체에서 발생하는 에러*

### ErrorBoundary 만들고 사용하는 방법

```swift
class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false };
  }

  static getDerivedStateFromError(error) {
    // 다음 렌더링에서 폴백 UI가 보이도록 상태를 업데이트 합니다.
    return { hasError: true };
  }

  componentDidCatch(error, errorInfo) {
    // 에러 리포팅 서비스에 에러를 기록할 수도 있습니다.
    logErrorToMyService(error, errorInfo); // sentry를 붙인다면...
  }

  render() {
    if (this.state.hasError) {
      // 폴백 UI를 커스텀하여 렌더링할 수 있습니다.
      return <h1>Something went wrong.</h1>;
    }

    return this.props.children;
  }
}
```

```swift
<ErrorBoundary>
  <MyWidget />
</ErrorBoundary>
```

에러 경계는 자바스크립트의 catch{} 구문과 유사하게 동작하지만 컴포넌트에 적용 됩니다. ***오직 클래스 컴포넌트만이 에러 경계가 될 수 있습니다.*** 실제로도 **대부분의 경우 에러 경계 컴포넌트를 한 번만 선언하여 애플리케이션 전체에서 활용하려고 할 것**입니다. 

**에러 경계는 트리 내에서 하위에 존재하는 컴포넌트의 에러만을 포착합니다**. 에러 경계 자체적으로는 에러를 포착할 수 없습니다. 에러 경계가 에러 메세지를 렌더링하는 데에 실패한다면 에러는 그 위의 가장 가까운 에러경계로 전파될 것입니다. 이 또한 자바스크립트의 catch {} 구문이 동작하는 방식과 유사합니다.

# 에러 경계를 배치할 위치

세분화 및 위치 선정은 개발자에 선택 사항 

- 최상위 경로의 컴포넌트를 감싸서 유저에게 메세지 보여줄 수 있다.
    
    ```tsx
    <ErrorBoundary>
    	<App />
    </ErrorBoundary>
    ```
    
- 부분 경계 가능
    
    ```tsx
    <App>
    	<ErrorBoundary>
    	  <p>These two counters are inside the same error boundary. If one crashes, the error boundary will replace both of them.</p>
    	  <BuggyCounter />
    	  <BuggyCounter />
    	</ErrorBoundary>
    	<hr />
    	<p>These two counters are each inside of their own error boundary. So if one crashes, the other is not affected.</p>
    	<ErrorBoundary><BuggyCounter /></ErrorBoundary>
    	<ErrorBoundary><BuggyCounter /></ErrorBoundary>
    </App>
    ```
    

# 포착되지 않는 에러에 대한 새로운 동작

React16부터는 에러 경계에서 포착되지 않은 에러로 인해 전체 React 컴포넌트 트리의 마운트 해제된다. 

예를들어 페이스북 메신저는 사이드 바, 정보 패널, 대화 기록과 메시지 입력을 각각 별도의 에러 경계로 감싸두었습니다. 이 UI영역 중 하나의 컴포넌트에서 충돌이 발생하면 나머지 컴포넌트는 대화형으로 유지 됩니다. 

프로덕션 환경에서 발생한 처리되지 않은 예외 상황에 대하여 학습하고 수정할 수 있도록 자바스크립트 에러 리포팅 서비스를 활용하거나 직접 작성하는 것을 권장 한다. [https://sentry.io/welcome/](https://sentry.io/welcome/)

# 컴포넌트 스택 추적

React16은 애플리케이션이 실수로 에러를 집어삼킨 경우에도 개발 과정에서 렌더링하는 동안 발생한 모든 에러를 콘솔에 출력합니다. 

![Untitled](Errorboundary%20ea349d969931455ebcfaf67967871586/Untitled.png)

또한 컴포넌트 스택 추적 내에서 **파일 이름과 줄 번호**도 확인할 수 있다. 이는 Create React App 프로젝트 내에서 기본적으로 동작한다. 

### 수동 설치 및 주의점

Create React App을 사용하지 않는 경우에는 수동으로 이 플러그인을 Babel 설정을 추가할 수 있다. 

이 기능은 개발 단계를 위해서만 제작되었으며 프로덕션 환경에서는 비활성화 해야 한다. 

# try/catch는 어떤가요?

try/catch는 훌륭하지만 명령형 코드에서만 동작 합니다.

```tsx
try {
  showButton();
} catch (error) {
  // ...
}
```

그러나 React 컴포넌트는 선언적이며 무엇을 렌더링할지 구체화 합니다. 

```tsx
<Button />
```

에러 경계는 React의 선언적인 특성을 보존하고 예상한 대로 동작합니다. 예를들어 트리의 깊숙한 어딘가에 있는 setState에 의해 유발된 componentDidUpdate 메서드에서 에러가 발생하더라도 가장 가까운 에러 경계에 올바르게 전달됩니다. 

# 이벤트 핸들러는 어떤가요?

에러 경계를 사용하지 않는 경우

```tsx
class MyComponent extends React.Component {
  constructor(props) {
    super(props);
    this.state = { error: null };
    this.handleClick = this.handleClick.bind(this);
  }

  handleClick() {
    try {
      // 에러를 던질 수 있는 무언가를 해야합니다.
    } catch (error) {
      this.setState({ error });
    }
  }

  render() {
    if (this.state.error) {
      return <h1>Caught an error.</h1>
    }
    return <button onClick={this.handleClick}>Click Me</button>
  }
}
```